*~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*
*  CLASS input parameter file (for energy injection with ExoCLASS) *
*~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*

root = output/test_cooling_wHe
#root = output/test_nodecay
overwrite_root = yes
output = tCl,lCl,pCl,mPk,Sd
write_distortions = yes

write background = yes
write parameters = yes

#####################Cosmo Parameters ########################

## NOTE THAT z reio is ignored !
omega_b = 0.02242
omega_cdm = 0.11933
h =0.6766
N_ur = 2.03351
N_ncdm = 1
m_ncdm = 0.06
k_pivot = 0.05
n_s = 0.9665
ln10^{10}A_s = 3.047

z_reio = 6.0
reio_parametrization = reio_camb
# recombination = recfast
########################Parameters for energy injection and recombinaison########################
# f_eff_type = DarkAges   #we use the DarkAges module to compute the energy deposition in the different channel. By default, it will return a table with (#z_dep	f_heat	f_lya	f_ionH	f_ionHe	f_lowE).
# DarkAges_mode = built_in   #default, can choose from user_command "built_in" or "user_command". see doc.

########################DM annihilation########################
#injected_particle_spectra = bottom tau photon
#injected_particle_branching_ratio = 0.25 0.25 0.5
# DM_annihilation_mass = 5  #GeV
# DM_annihilation_cross_section = 3e-24 #cm^3s^-1
# DM_annihilation_fraction = 1
########################DM decay########################
# DM_decay_mass = 0.1
# DM_decay_mass = 0.4   #GeV
# DM_decay_Gamma = 3.333e-26
# DM_decay_Gamma = 8.009611533840608e-26 #s^-1

# DM_decay_mass = 448   #GeV
# DM_decay_Gamma = 8.333333333333334e-26
# DM_decay_fraction = 1
# injected_particle_spectra = dirac_photon
# injected_particle_branching_ratio = 1
# include_DH_SMresidual_distortions = yes
# add_SD_to_CLASS = yes
# sd_z_min = 3
# sd_z_size = 1000

#sd_z_max = 3000
# sd_x_size = 100
# apply_smoothing = yes
# nbins_smoothing = 100
########################PBH evaporation########################
# PBH_evaporation_fraction = 1e-5
# PBH_evaporation_mass = 1e15 #in g

########################PBH accretion########################
# PBH_accretion_fraction = 1e-5
# PBH_accretion_mass = 1e3 #in Msun
# PBH_accretion_recipe = spherical_accretion


#####user command#####
# >> Run the "simple_mix" model: Th model takes two input parameters:
# >> 1) The mass of the DM-candidat in GeV [50,100]
# >> 2) The branching ratio of muons as primaries (1 - branching ratio of bottoms as primaries) [0,1]
#

# f_eff_type = DarkAges
# DarkAges_mode = built_in
# DarkAges_command = ./external_fz/bin/DarkAges -m simple_mix
# ext_fz_par1 = 57.32
# ext_fz_par2 = 0.723

include_reionization_from_stars = yes
include_recombination_cooling = yes
#sd_add_y = 2.0708e-08
stars_photoion_file = /Users/viviesque/Documents/GitHub/ExoCLASS_perso/external/heating/photoion_rates_Puchwein.dat
stars_photoheat_file = /Users/viviesque/Documents/GitHub/ExoCLASS_perso/external/heating/photoheat_rates_Puchwein2.dat
DH_He_file_name = /Users/viviesque/Documents/GitHub/ExoCLASS_perso/external/heating/xHe_DarkHistory.txt
########################additional parameters########################
## To compute SD with darkages, set to yes.
# compute_SD_with_DarkAges=yes
# sd_branching_approx= sharp_sharp

write thermodynamics = yes
input_verbose = 1
background_verbose = 1
thermodynamics_verbose = 1
perturbations_verbose = 1
transfer_verbose = 1
primordial_verbose = 1
spectra_verbose = 1
nonlinear_verbose = 1
lensing_verbose = 1
output_verbose = 1
write warnings = yes
distortions_verbose = 1
hyrec_verbose =1
